import { Inter } from "next/font/google";
import "./globals.css";
import ReducProvider from "@/utils/ReducProvider";
import ProtecterRoute from "@/utils/ProtecterRoute";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      
      <body className={inter.className}>
        <ReducProvider>
          <ProtecterRoute>
          <Header/>
          {children}
          <Footer/>
          </ProtecterRoute>
        </ReducProvider>
        </body>
       
    </html>
  );
}
